server:
  port: 8888
spring:
  datasource:
    url: url
    username: postgres
    password: password
  jpa:
    generate-ddl: true
  flyway:
    enabled: false
  #todo 14.04.2021 (мне) гаписать проприс для JavaMailSender'a.